version: "3.9"

services:
  dockerd:
    image: docker:dind
    privileged: true
    hostname: dockerd
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    expose:
      - 2376
  docker:
    image: docker
    tty: true
    environment:
      - DOCKER_HOST=tcp://dockerd:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - docker-certs-client:/certs/client:ro
    depends_on:
      - dockerd
  devenv:
    image: ubuntu
    tty: true
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock 
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - ~/.gitconfig:/root/.gitconfig
      - workspace:/workspace

volumes:
  workspace:
  docker-certs-ca:
  docker-certs-client:

# https://github.com/docker/for-mac/issues/483#issuecomment-620229892
